before_install: cd travis-ci
language: ruby
rvm:
- 2.3.0
- jruby-19mode
- rbx-2
script:
- bundle install — jobs=3 — retry=3
- bundle exec rake db:create
 # — bundle exec rake db:migrate
 # — bundle exec rspec

